AWSTemplateFormatVersion: '2010-09-09'
Description: S3 + CloudFront hosting for Angular SPA
Parameters:
  DomainName: { Type: String }
  AltDomain: { Type: String, Default: !Sub 'www.${DomainName}' }
  CertificateArn: { Type: String, Description: 'ACM in us-east-1' }
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName
      OwnershipControls: { Rules: [ { ObjectOwnership: BucketOwnerEnforced } ] }
      PublicAccessBlockConfiguration: { BlockPublicAcls: true, BlockPublicPolicy: true, IgnorePublicAcls: true, RestrictPublicBuckets: true }
      VersioningConfiguration: { Status: Enabled }
  OAC: { Type: AWS::CloudFront::OriginAccessControl, Properties: { OriginAccessControlConfig: { Name: !Sub '${DomainName}-oac', OriginAccessControlOriginType: s3, SigningBehavior: always, SigningProtocol: sigv4 } } }
  Dist:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Aliases: [ !Ref DomainName, !Ref AltDomain ]
        ViewerCertificate: { AcmCertificateArn: !Ref CertificateArn, SslSupportMethod: sni-only, MinimumProtocolVersion: TLSv1.2_2021 }
        DefaultCacheBehavior:
          TargetOriginId: s3origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [ GET, HEAD, OPTIONS ]
          CachedMethods:  [ GET, HEAD, OPTIONS ]
          Compress: true
          ForwardedValues: { QueryString: false }
        Origins:
          - Id: s3origin
            DomainName: !GetAtt Bucket.RegionalDomainName
            S3OriginConfig: {}
            OriginAccessControlId: !Ref OAC
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
Outputs:
  BucketName: { Value: !Ref Bucket }
  DistributionId: { Value: !Ref Dist }
  DistributionDomain: { Value: !GetAtt Dist.DomainName }
